@echo off
echo Starting Next.js frontend...
start cmd /k "cd frontend && node node_modules\next\dist\bin\next dev"

echo Waiting a moment to ensure ports are ready...
timeout /t 3

echo Importing Article Ingestion Workflow into n8n...
call npx n8n import:workflow --input=1-ingestion_workflow.json

echo Importing SEO Processing Workflow into n8n...
call npx n8n import:workflow --input=2-seo_processing_workflow.json

echo Booting n8n server on localhost:5678...
call npx n8n
